### ISSUE TITLE
相談: peerDependencyの活用

### ISSUE THREAD

**Issue by ToyB0x** [3-shake/3design-ui#580]
Issueというよりは相談なのですが、
現在Securify側ではMUIを直接使わざるを得ない箇所があり、Nextアプリのdependenciesに指定しています。

3desing-ui側もdependenciesにMUIを追加しているかと思うのですが、その両方が原因となり、
添付画像のように二つのMUIがnode_modulesに含まれている状況です。

[Next.jsのpeerDependencies](https://github.com/vercel/next.js/blob/3069d4b77017228c86ec87238864a226efb092ae/packages/next/package.json#L77-L83)のように、3desing-ui側もpeerDependencies化が可能かと思うのですがどうでしょう？
(dependencies --> peer / devDependenciesに移動できれば一つのアプリで二つのMUIを使う状況を防止できるかと思います)

### 3design-ui側のMUI
![image](https://user-images.githubusercontent.com/83337042/161208653-cc91fc9e-6ec0-4338-8924-980d6d281d03.png)

### securify側のMUI
![image](https://user-images.githubusercontent.com/83337042/161208693-c7eb3aec-6765-4ad6-8ae0-5412d42ae3a9.png)

**Comment by locona** [comment]
@ToyB0x 
以下でリリースしました
2.0.0-beta.1

**Comment by ToyB0x** [comment]
ありがとうございます！ 🙇‍♂️ 
後ほど更新してみます！
